"""
This module provides a method to read the output of Variant Effect
Predictor command line annotation on VCF files, when using the
option --tab (which generates a TSV file).
"""
import pandas as pd


def read_VEP_header(fn):
    """Reads the header of a Variant Effect Predictor generated tab file."""
    with open(fn) as f:
        for line in f:
            if not line.startswith('##'):
                break

    return line.strip()[1:].split('\t')  # [1:] Removes leading '#'


def read_VEP_table(fn, keep_only_canonical=True):
    """
    Reads a table of annotations as generated by Variant Effect Predictor
    command line script with the option --tab.

    If you annotated the variants with the option --everything or --canonical,
    keep_only_canonical=True will keep only the annotations of canonical
    transcripts. Set as False to get all transcripts annotations.
    """
    fields = read_VEP_header(fn)
    df = pd.read_table(fn, names=fields, comment='#')
    if keep_only_canonical:
        df = df[df['CANONICAL'] == 'YES'].reset_index(drop=True)
    return df

